#!/bin/sh

JAVA_CMD="/usr/bin/java"
JAVA_OPTS=""
JAVA_CLASSPATH="/opt/local/share/java/rhino/js.jar:/Users/james/IBM/Code/dwb/WebContent/WEB-INF/lib/shrinksafe.jar"
JAVA_MAIN="org.mozilla.javascript.tools.debugger.Main"

$JAVA_CMD $JAVA_OPTS -classpath $JAVA_CLASSPATH $JAVA_MAIN $@
